# Generated by Django 4.2 on 2023-04-23 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_identifyer', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='created')),
                ('quantity', models.IntegerField()),
                ('value_unit', models.DecimalField(decimal_places=3, max_digits=10)),
                ('operation', models.CharField(choices=[('C', 'Compra'), ('V', 'Venda')], max_length=1)),
                ('value_brokerage', models.DecimalField(decimal_places=3, max_digits=10)),
                ('value_operation', models.DecimalField(decimal_places=3, max_digits=10)),
                ('b3_rate', models.DecimalField(decimal_places=3, max_digits=10)),
                ('value_total', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b3investmanager.code')),
            ],
        ),
    ]
