# Generated by Django 4.2 on 2023-04-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b3investmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='investment_identifyer',
            field=models.CharField(default='no specified', max_length=50),
        ),
    ]
