# Generated by Django 4.1.7 on 2023-04-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investidor',
            name='perfil',
            field=models.CharField(choices=[('C', 'Conservador'), ('M', 'Moderado'), ('A', 'Arrojado')], max_length=1),
        ),
    ]
