# Generated by Django 4.1.7 on 2023-05-01 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_wallet', '0002_alter_investidor_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='corretagem',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
